### ISSUE TITLE
Impossible d'installer OpenplacOs

### ISSUE THREAD

**Issue by opengard** [openplacos/openplacos#13]
Bonjour ! 

Malgré de nombreuses tentatives d'installations, le logiciel semble ne plus pouvoir s'installer (problème de dépendances). Je suis sous Ubuntu 14.04, le problème semble venir de start-stop-daemon : "Les paquets suivants contiennent des dépendances non satisfaites : openplacos : Dépend: start-stop-daemon mais il n'est pas installable", pouvez-vous m'aider dans la résolution de ce problème ? 

Merci.

**Comment by flagos** [comment]
Salut, 

Je te remercie pour ton rapport de bug. J'ai fixé le souci sur le package. Tu peux réessayer de l'installer en faisant un apt-get update avant.

Par contre, je rencontre un autre souci sur la suite de l'installation (je t'avoue utiliser openplacos sans trop utiliser le packet ppa mais directement a partir des sources), si à tout hasard tu les rencontres également n'hesite pas a revenir sur ce thread.

**Comment by opengard** [comment]
Merci d'avoir pris le temps de répondre et de corriger l'erreur ! 

Effectivement, l'erreur de départ est résolue, mais une autre apparaît par la suite (comme tu le dis).

Voici ce que le terminal m'indique : 

"Your Gemfile.lock is corrupt. The following gems are missing from the
DEPENDENCIES section: 'contest' 'sr-mg' 'redgreen'
L'utilisateur système « openplacos » existe déjà. Fin de la procédure.
L'utilisateur « openplacos » appartient déjà au groupe « dialout ».
update-rc.d: warning: /etc/init.d/openplacos missing LSB information
update-rc.d: see <http://wiki.debian.org/LSBInitScripts>
 System start/stop links for /etc/init.d/openplacos already exist."

J'espère que le problème peut se résoudre également, j'ai hâte de pouvoir utiliser votre soft ! ;)

**Comment by flagos** [comment]
Bonjour, 

Le bug (la dernière version de bundler en 1.11.X a regressée, rollback sur la 1.10.6 en attedant) a été fixée sur le ppa avec la version openplacos_0.4+557~ubuntu14.04.1_all.deb.

Merci de ta patience et de ton bug report.
