### ISSUE TITLE
Impossible de lancer OpenplacOs

### ISSUE THREAD

**Issue by opengard** [openplacos/openplacos#14]
Bonjour et bonne année, 

Je suis venu ici il y a quelques jours pour des problèmes lors de l'installation, merci déjà d'avoir pris le temps de corriger cela. 
Je suis encore obligé de venir vers vous car cette fois, c'est le lançage du programme qui pose problème. Une fois l'installation terminée, je lance la commande "openplacos" et le terminal me demande un username et un password (oauth2 ?), sauf que je n'ai renseigné ces informations nul part...(et laisser les champs vides ne fonctionne pas). Je ne vois vraiment pas comment lancer le logiciel, d'ailleurs j'ai cru voir sur la vidéo de présentation à la RMLL une interface graphique avec un système de "glissé-déposé", est-ce bien cela qui doit lancer la commande "openplacos" ? 

J'espère que tu pourras m'éclaire sur tout cela :D 
Bonne fin de journée.

**Comment by opengard** [comment]
Bonjour, 

As-tu trouvé une solution au problème ? 
J'attend ta réponse avec impatience ;) 

Bon week-end !

**Comment by opengard** [comment]
Bonjour,

J'ai essayé l'installation depuis d'autres ordinateurs, toujours en effectuant les commandes suivantes : 
sudo add-apt-repository ppa:openplacos/ppa
sudo apt-get update
sudo apt-get install openplacos

Aucun message d'erreur mais pourtant lors du lancement de l'application, je dois rentrer un username et un mot de passe qui ne me sont pas réclamés lors de l'installation... 
Je ne pense pas que ce soit normal, à moins que je m'y prenne mal. Peux-tu m'éclairer à ce sujet ?

Bien cordialement.

**Comment by flagos** [comment]
Salut,

Désolé j'ai trainé un peu pour te répondre, le couple login/password est
"root"/" root".

Après je pense que tu vas t'en rendre compte par toi même, mais opos est un
peu abandonné dans le sens où on a jamais réussi à faire l'interface qu'on
a présenté au rmll, principalement du au framework qui était bien trip
buggue.

Pour autant, il s'agit que d'une interface de configuration pour générer un
fichier .yaml dont tu as un exemple avec le fichier de configuration par
défaut, je t'invite à regarder et à la faire à la main, ça se fait pas trop
mal.

Une fois cette étape de configuration passée, le logiciel marche plutôt
bien, on s'en sert régulièrement pour brasser de la bière ;-)

**Comment by opengard** [comment]
Re

Merci d'avoir pris le temps de répondre, je suis cependant ennuyé car le couple root/root ne fonctionne pas :/

automat@automat-Compaq-Mini-311-1100:~$ openplacos
Enter your username:  root
Enter your password:  
Authentification failure

J'espère pouvoir en faire de même un jour ;)

**Comment by opengard** [comment]
Salut, 

Désolé de devoir revenir vers toi mais le projet que j'entreprend arrive à sa fin, il ne manque plus que la partie logiciel : openplacos. J'ai donc vraiment besoins du couple user/password (qui ne semble pas être root/root), as-tu une solution ? 
Merci de ton aide.

**Comment by flagos** [comment]
Tu fais bien de me relancer. J'ai pas réessayé avec le client en CLI depuis un moment, notamment car une fois accordé, il ne redemandait plus l'accès. J'essaierai de regarder ca ce soir.

Pour autant, as tu accès à la web interface ? http://0.0.0.0:4567

**Comment by opengard** [comment]
Pas d'accès à l'interface web non plus, message d'erreur "la connexion a échoué......"

**Comment by flagos** [comment]
Il n'y a aucune erreur lorsque tu lances: 
# /etc/init.d/openplacos start

**Comment by opengard** [comment]
automat@automat-Compaq-Mini-311-1100:~$ sudo /etc/init.d/openplacos start
[sudo] password for automat: 
Starting OpenplacOS
Pas de répertoire, connexion avec HOME=/
No protocol specified
automat@automat-Compaq-Mini-311-1100:~$ Error:: Config file /etc/default/openplacos doesn't exist

**Comment by flagos** [comment]
Manifestement, ton installation s'est mal déroulée car il te manque le fichier de configuration, certainement du au premier bug que tu m'as rapporte.

Fais un purge, suivi d'une réinstalle du paquet, et retente de te connecte sur la web page.

**Comment by opengard** [comment]
Je viens de faire :

apt-get purge openplacos
reboot
add-apt-repository ppa:openplacos/ppa
apt-get update
apt-get install openplacos


Aucunes améliorations lorsque j'essaye de lancer openplacos, ni même lorsque j'essaye d'ouvrir l'interface web et non plus lorsque je fais /etc/init.d/openplacos start

Est-ce que je m'y suis mal pris ou le problème vient d'autre part ?

**Comment by flagos** [comment]
Il semblerait que le script d'installation ne fasse pas la copie du fichier de config par défaut, pour éviter que celui ci soit écrasé au moment d'un update.

Il faut donc faire une étape manuelle, non décrite dans la doc:
$ cp /usr/lib/ruby/openplacos/config/default.yaml /etc/default/openplacos 

Si tu n'as bien pas d'erreur au moment de l'install, je pense que ton souci vient de la. Je vais ajuster la doc si tu me confirmes que ca resout ton souci.

**Comment by opengard** [comment]
Ok, maintenant l'interface web s'ouvre ! 
Merci :) 

Les onglets permettent de gérer la température, l'humidité, la ventilation et la lumière. Pour rajouter des capteurs/regulations, il faut s'y prendre depuis l'interface web ou depuis un terminal ?

**Comment by flagos** [comment]
victoire :-)

Pour ajouter des fonctionnalites, tout se passe dans le fichier de config aue tu viens de copier. Je t'invite à lire la doc: https://github.com/openplacos/openplacos#config-file

N'hesite pas revenir poser des questions si toutefois tu ne comprends. J'ai fait un petit effort sur cette doc mais il n'est pas impossible qu'elle ne soit pas claire et je n'ai pas beaucoup de feedback sur celle-ci.

**Comment by opengard** [comment]
Super merci !
Je te tiendrais au jus une fois avoir configuré tout cela ;)

**Comment by opengard** [comment]
La doc que tu as faite me semble claire, je coince juste sur la modification du fichier de config car c'est Impossible d'enregistrer les modifs ! En même temps, je ne suis vraiment pas certain d'avoir "modifié" le bon fichier, si tu pouvais rajouter dans la doc où et comment trouver le fichier de config à modifier pour ajouter des fonctionnalités ce serait top ;)

**Comment by flagos** [comment]
Ajouté dans la doc.

Pour les droits, effectivement le fichier est peut etre en lecture simple, un petit chmod +r peut aider.

**Comment by opengard** [comment]
Je ne mettais pas trompé de fichier, c'est déjà ça. 

j'ai effectué un chmod a+w (pourquoi +r si l'on souhaite donner les droits d'écritures ?), cela ne resoud pas le problème puisque lorsque j'enregistre, le message suivant apparaît : "Impossible de créer un fichier de sauvegarde lors de l'enregistrement de « /etc/default/openplacos »". Apres fermeture (sans enregistrement) du fichier, clic droit puis permissions je tombe sur "vous n'êtes pas le propriétaire de cet élément, vous ne pouvez donc pas en changer les permissions"... Nouvelle impasse.

**Comment by flagos** [comment]
Désolé +w, évidemment. Tu as certainement fait la copie en étant root, puisque je crois que par défaut seul le root peut ecrire dans /etc/default/. 

Pour connaitre le owner, fais un $ ls -l /etc/default/openplacos # mais à priori c'est root.
Et ensuite, en tant que root, tu l'édites en mode $ sudo nano /etc/default/openplacos ou $ gksudo gedit /etc/default/openplacos # si tu préfères un éditeur graphique

**Comment by opengard** [comment]
Super, l'enregistrement fonctionne. 

Bien maintenant je vais prendre le temps de comprendre tout cela car malgré la clarté de la doc, entre la théorie et l'application c'est loin d'être gagné... ^^
